version: "3.3"
services:

  gateway:
    build:
      context: ./gateway/docker/nginx
    ports:
      - "8082:8082"
      - "8083:8083"
      - "8025:8025"

    depends_on:
      - frontend
      - api

  # api

  api:
    build:
      context: ./api/docker/nginx
    volumes:
      - ./api:/app/
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: ./api/docker
      dockerfile: ./php-fpm/Dockerfile
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: "api-postgres"
      DB_USER: "nana"
      DB_PASSWORD: "123456"
      DB_NAME: "app"
      MAILER_HOST: "mailer"
      MAILER_PORT: 1025
      MAILER_USERNAME: "app"
      MAILER_PASSWORD: "secret"
      MAILER_ENCRYPTION: "tcp"
      MAILER_FROM_EMAIL: "mail@app.test"
    volumes:
      - ./api:/app/

  api-php-cli:
    build:
      context: ./api/docker
      dockerfile: ./php-cli/Dockerfile
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      DB_HOST: "api-postgres"
      DB_USER: "nana"
      DB_PASSWORD: "123456"
      DB_NAME: "app"
      #      MAILER_HOST: "smtp.mailtrap.io"
      #      MAILER_PORT: 25
      #      MAILER_USERNAME: "b3dedfc298c893"
      #      MAILER_PASSWORD: "568ed55f250b42"
      #      MAILER_ENCRYPTION: "tls"
      MAILER_HOST: "mailer"
      MAILER_PORT: 1025
      MAILER_USERNAME: "b3dedfc298c893"
      MAILER_PASSWORD: "568ed55f250b42"
      MAILER_ENCRYPTION: "tcp"
      MAILER_FROM_EMAIL: "mail@app.test"
    volumes:
      - ./api:/app/

  api-postgres:
    build:
      context: ./api/docker/postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "nana"
      POSTGRES_DB: "app"
    volumes:
      - ./api/docker/postgres/data:/var/lib/postgresql/data
    depends_on:
      - api

  #  frontend
  frontend:
    build:
      context: ./frontend/docker/nginx
    volumes:
      - ./frontend:/app/
    depends_on:
      - frontend-node-cli
      - frontend-node-server

  frontend-node-cli:
    build:
      context: ./frontend/docker/node
    volumes:
      - ./frontend:/app

  # 3000 port, see gateway
  frontend-node-server:
    build:
      context: ./frontend/docker/node
    volumes:
      - ./frontend:/app

    # .ready file is created after frontend-yarn-install command is done, so we do yarn start only when all dependencies are installed
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    tty: true

  # services
  mailer:
    image: mailhog/mailhog