site:
	ansible-playbook -i hosts.yaml site.yaml

renew-certificates:
	ansible-playbook -i hosts.yaml renew-certificates.yaml

authorize:
	ansible-playbook -i hosts.yaml authorize.yaml

docker-login:
	ansible-playbook -i hosts.yaml docker-login.yaml

